<h3>Logical Arrays</h3>

In [1]:
import numpy as np

In [2]:
## what is the output?

a=np.array([True, False, 1, 0, 'a' in "abc", 3==4, 7<8, 3 in {1,2}, 
            {1}<={1,2}, not True, True or False, True and False], dtype=bool)  ## specify dtype=bool
"""
[True, False, True, False, True, False, True, False, True, False, True, False]]
"""
print(a)

[ True False  True False  True False  True False  True False  True False]


In [5]:
## element-wise comparisons
## i.e., simultaneously applies question to corresponding values in arrays, 
## without using indexing and loops (faster!)
## organizes answers in a logical array the same size as a and b

a=np.array([2, 4, 7])
b=np.array([8, 4, 6])

larger=(a>b)  ## how would you describe in words what this line of code does?

"""Performs element wise greater than comparison"""
equal=(a==b)  ## (you don't need the brackets, but it helps me visually)

print(larger)  ## or simply, print(a>b)
print(equal)   ## or print(a==b)

[False False  True]
[False  True False]


In [6]:
## not/and/or applied element-wise; returns a logical array the same size as c and d 

c=np.array([True, True, False], dtype=bool)
d=np.array([False, True, True], dtype=bool)

print(np.logical_not(c),'\n')  # what does this do?
"""inverse of all values, [False, False, True]"""
print(np.logical_and(c,d),'\n')  # are the elements c[i] and d[i] True?
"""element wise and: [False, True, False]"""
print(np.logical_or(c,d),'\n')  # is the element c[i] or d[i] True?
"""element wise or: [True, True, True]"""

[False False  True] 

[False  True False] 

[ True  True  True] 



'element wise or: [True, True, True]'

In [7]:
## apply question to each element in array; return True or False
## simultaneously tests all values in an array, without using a loop (faster!)

a=np.array([2, 4, 7])
print(a,'\n')
print(a>4,'\n')
print(a<3,'\n')
print(np.logical_or(a>4, a<3),'\n')
print(np.logical_and(a>4, a<3))

[2 4 7] 

[False False  True] 

[ True False False] 

[ True False  True] 

[False False False]


In [8]:
## apply question to each element in a higher dimensional array; return True or False
## returns a logical array with the same dimensions as a

a=np.array([[6, 4,12,-4], [5, 9,10,7.4], [45, -9,13,8.0]], dtype=float)
print(a,'\n')
print(a>=6)

[[ 6.   4.  12.  -4. ]
 [ 5.   9.  10.   7.4]
 [45.  -9.  13.   8. ]] 

[[ True False  True False]
 [False  True  True  True]
 [ True False  True  True]]


In [9]:
## creating a new array from an old one, using entries that satisfy some criterion/criteria
## (extracting entries from an array which satisfy some criterion/criteria)

a=np.arange(12).reshape(3,4)
print(a,'\n')

b=(a>4)  ## logical array with the same dimensions as a
print(b,'\n')

print(a[b])  ## prints a 1-dimensional array consisting of values from a where corresponding b-value is True

# can you compress this code?

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]] 

[ 5  6  7  8  9 10 11]


In [10]:
## creating an new array from an old one, using entries that satisfy some criterion/criteria
## (extracting entries from an array which satisfy some criterion/criteria)

a=np.array([[6, 4,12,-4], [5, 9,10,7.4], [45, -9,13,8.0]], dtype=float)
print(a,'\n')

print(a[a>=6],'\n') # what will the output be?
print(a[a>=11],'\n')  # note shape of array (1D)
print(a[a<-10],'\n')  
print(a[np.logical_and(5<a,a<9)])

[[ 6.   4.  12.  -4. ]
 [ 5.   9.  10.   7.4]
 [45.  -9.  13.   8. ]] 

[ 6.  12.   9.  10.   7.4 45.  13.   8. ] 

[12. 45. 13.] 

[] 

[6.  7.4 8. ]


In [ ]:
## reassigning all values in an array which satisfy some criterion 

a=np.arange(12).reshape(3,4)
print(a,'\n')

print(a[a>6],"\n")  ## prints a 1D array containing values >6 from a

a[a>6]=0  ## updates entries in original array a (here, we replace True entries with 0) 
print(a)  ## recall: arrays are mutable!

In [ ]:
## SUMMARY

a=np.arange(12).reshape(4,3)  ## original 2D array
print("a= \n", a, "\n")

print(a>=3, "\n")  ## 2D logical array, same dimensions as original

print(a[a>=3], "\n")  ## extracting values from a which are >=3 and creating a 1D logical array

a[a>=6]=0  ## updating values which are >=3 in the original 2D array
print(a)

<b>EXERCISES</b>

In [12]:
## exercise - what does this code do?

a=np.arange(28).reshape(4,7) #from 0-27 it then creates a matrix of 4 rows, 7 cols
print(a,'\n')

b=(a%3==0) # Creates a matrix of booleans, satisfying the requirements
print(b,'\n')

a[b]=100  #Replaces all satisfying indicies with 100
print(a)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]] 

[[ True False False  True False False  True]
 [False False  True False False  True False]
 [False  True False False  True False False]
 [ True False False  True False False  True]] 

[[100   1   2 100   4   5 100]
 [  7   8 100  10  11 100  13]
 [ 14 100  16  17 100  19  20]
 [100  22  23 100  25  26 100]]


In [13]:
## any/all method applied to arrays

a=np.array([2, 4, 7])
b=np.array([8, 4, 6])

print(a<=b)
print(np.any(a<=b))  # are any True?
print(np.all(a<=b))  # are all True?

## exercise: write code to do what np.any(a<=6) and np.all(a<=6) do, without using np.any or np.all
for n in a:
    if n <= 6:
        print(True)
print(False)




[ True  True False]
True
False
True
True
False


In [21]:
## exercise: given a numpy array, find the sum of all negative terms

a=np.arange(-4,6).reshape(2,5)
print(a,'\n')
con = a<0

print(a[con],'\n')
sum = np.sum(a[con])
print(sum,'\n')


[[-4 -3 -2 -1  0]
 [ 1  2  3  4  5]] 

[-4 -3 -2 -1] 

-10 



<u>APPLICATION: GRID METHOD FOR SOLVING f(x)=0 </u>

In [22]:
# RECALL - grid method for solving f(x)=0 
# scan a given interval [a,b] for possible solutions

def f(x):
    return x**3-3.397*x**2+3.42254*x-0.9528992  ##  =(x-0.46)*(x-1.177)*(x-1.76)

a=0
b=10
n=5000000   
dx=(b-a)/n
tol=1e-7   

solution_found=False
for i in range (0,n+1):
    if abs(f(a+i*dx))<tol:
        print("possible solution",a+i*dx, "value of f:",f(a+i*dx))
        solution_found=True

if not solution_found:
    print("solution not found; increase n")

possible solution 0.45999999999999996 value of f: 2.220446049250313e-16
possible solution 1.177 value of f: 9.992007221626409e-16
possible solution 1.76 value of f: 1.887379141862766e-15


In [23]:
# example: using logical arrays to solve equations
# revisiting the grid method
# for real, with a large number of grid points
# need to experiment with the number of grid points and tolerance

gridpoints=5000000
tol=1e-7

x=np.linspace(0,2,gridpoints)
y=f(x)   ## y=(x-0.46)*(x-1.177)*(x-1.76)

root=(abs(y)<tol)  ## root = corresponding logical array for y (same dimensions as y)

print('\n  y-value(s) where the root(s) is/are: \n',y[root])  # extracts values from y where coorresponding value in 'root' is True
print('\n  x-value(s) where the root(s) is/are: \n',x[root])  


  y-value(s) where the root(s) is/are: 
 [ 8.57532003e-08  6.88046283e-08 -9.83998011e-08 -3.63792018e-08]

  x-value(s) where the root(s) is/are: 
 [0.46000009 1.17699984 1.17700024 1.75999995]
